name: hello-world-example
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Say Hello
        run: echo "Hello world RG!"
      -
        name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
      -
        name: Say Goodbye
        run: echo "Goodbye!"
